apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "web.fullname" . }}-web-assets"
  labels:
    backupType: {{ .Values.threefoldVdc.backup | quote }}
spec:
  capacity:
    storage: {{ .Values.web.persistentVolume.assets.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.web.persistentVolume.assets.accessMode | quote }}
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: {{ .Values.web.persistentVolume.assets.hostPath }}
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "web.fullname" . }}-assets
spec:
  accessModes:
    - {{ .Values.web.persistentVolume.assets.accessMode | quote }}
  resources:
    requests:
      storage: "{{ .Values.web.persistentVolume.assets.size }}"
  storageClassName: ""
  volumeName: "{{ include "web.fullname" . }}-web-assets"
